### ISSUE TITLE
Unable to yarn install?

### ISSUE THREAD

**Issue by isaaclem** [aws-samples/aws-mobile-react-native-notes-tutorial#6]
```
warning Error running install script for optional dependency: "/Users/lemchiewchoon/Code/ReactNative/aws-mobile-react-native-notes-tutorial/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/lemchiewchoon/Code/ReactNative/aws-mobile-react-native-notes-tutorial/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.38
node-pre-gyp info using node@9.8.0 | darwin | x64
node-pre-gyp info check checked for \"/Users/lemchiewchoon/Code/ReactNative/aws-mobile-react-native-notes-tutorial/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.8.0 (node-v59 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/lemchiewchoon/Code/ReactNative/aws-mobile-react-native-notes-tutorial/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:379:16)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:114:19)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command \"/usr/local/lib/node_modules/node/bin/node\" \"/Users/lemchiewchoon/Code/ReactNative/aws-mobile-react-native-notes-tutorial/node_modules/fsevents/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/lemchiewchoon/Code/ReactNative/aws-mobile-react-native-notes-tutorial/node_modules/fsevents
node-pre-gyp ERR! node -v v9.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)"
```

I'm hitting exceptions after cloning the project and executing `yarn install`.
Node version is v9.8.0 on MacOS

**Comment by adrianhall** [comment]
Seems yarn + fsevents on MacOSX has an issue.  Run `npm install` instead - it works.

Unfortunately, since this is deep in the dependencies tree, there isn't much I can do about it.
